version: '3.8'

services:
  gotit-api-javascript-sdk-example:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development
    restart: unless-stopped 