/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import STORESSCHEMA from './STORESSCHEMA';
import USAGEMETHODSCHEMA from './USAGEMETHODSCHEMA';

/**
 * The BRANDDETAIL model module.
 * @module model/BRANDDETAIL
 * @version 4.0.0
 */
class BRANDDETAIL {
    /**
     * Constructs a new <code>BRANDDETAIL</code>.
     * @alias module:model/BRANDDETAIL
     */
    constructor() { 
        
        BRANDDETAIL.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BRANDDETAIL</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BRANDDETAIL} obj Optional instance to populate.
     * @return {module:model/BRANDDETAIL} The populated <code>BRANDDETAIL</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BRANDDETAIL();

            if (data.hasOwnProperty('brandId')) {
                obj['brandId'] = ApiClient.convertToType(data['brandId'], 'Number');
            }
            if (data.hasOwnProperty('brandNm')) {
                obj['brandNm'] = ApiClient.convertToType(data['brandNm'], 'String');
            }
            if (data.hasOwnProperty('brandAddr')) {
                obj['brandAddr'] = ApiClient.convertToType(data['brandAddr'], 'String');
            }
            if (data.hasOwnProperty('brandLogo')) {
                obj['brandLogo'] = ApiClient.convertToType(data['brandLogo'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('shortDesc')) {
                obj['shortDesc'] = ApiClient.convertToType(data['shortDesc'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('categoryID')) {
                obj['categoryID'] = ApiClient.convertToType(data['categoryID'], [Object]);
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'Number');
            }
            if (data.hasOwnProperty('serviceGuide')) {
                obj['serviceGuide'] = ApiClient.convertToType(data['serviceGuide'], 'String');
            }
            if (data.hasOwnProperty('stores')) {
                obj['stores'] = ApiClient.convertToType(data['stores'], [STORESSCHEMA]);
            }
            if (data.hasOwnProperty('usageMethods')) {
                obj['usageMethods'] = ApiClient.convertToType(data['usageMethods'], [USAGEMETHODSCHEMA]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BRANDDETAIL</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BRANDDETAIL</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['brandNm'] && !(typeof data['brandNm'] === 'string' || data['brandNm'] instanceof String)) {
            throw new Error("Expected the field `brandNm` to be a primitive type in the JSON string but got " + data['brandNm']);
        }
        // ensure the json data is a string
        if (data['brandAddr'] && !(typeof data['brandAddr'] === 'string' || data['brandAddr'] instanceof String)) {
            throw new Error("Expected the field `brandAddr` to be a primitive type in the JSON string but got " + data['brandAddr']);
        }
        // ensure the json data is a string
        if (data['brandLogo'] && !(typeof data['brandLogo'] === 'string' || data['brandLogo'] instanceof String)) {
            throw new Error("Expected the field `brandLogo` to be a primitive type in the JSON string but got " + data['brandLogo']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['shortDesc'] && !(typeof data['shortDesc'] === 'string' || data['shortDesc'] instanceof String)) {
            throw new Error("Expected the field `shortDesc` to be a primitive type in the JSON string but got " + data['shortDesc']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['categoryID'])) {
            throw new Error("Expected the field `categoryID` to be an array in the JSON data but got " + data['categoryID']);
        }
        // ensure the json data is a string
        if (data['serviceGuide'] && !(typeof data['serviceGuide'] === 'string' || data['serviceGuide'] instanceof String)) {
            throw new Error("Expected the field `serviceGuide` to be a primitive type in the JSON string but got " + data['serviceGuide']);
        }
        if (data['stores']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['stores'])) {
                throw new Error("Expected the field `stores` to be an array in the JSON data but got " + data['stores']);
            }
            // validate the optional field `stores` (array)
            for (const item of data['stores']) {
                STORESSCHEMA.validateJSON(item);
            };
        }
        if (data['usageMethods']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['usageMethods'])) {
                throw new Error("Expected the field `usageMethods` to be an array in the JSON data but got " + data['usageMethods']);
            }
            // validate the optional field `usageMethods` (array)
            for (const item of data['usageMethods']) {
                USAGEMETHODSCHEMA.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Brand id
 * @member {Number} brandId
 */
BRANDDETAIL.prototype['brandId'] = undefined;

/**
 * Brand name
 * @member {String} brandNm
 */
BRANDDETAIL.prototype['brandNm'] = undefined;

/**
 * Address of brand
 * @member {String} brandAddr
 */
BRANDDETAIL.prototype['brandAddr'] = undefined;

/**
 * Link to brand logo image
 * @member {String} brandLogo
 */
BRANDDETAIL.prototype['brandLogo'] = undefined;

/**
 * Brand name used for URL
 * @member {String} slug
 */
BRANDDETAIL.prototype['slug'] = undefined;

/**
 * Brand short description
 * @member {String} shortDesc
 */
BRANDDETAIL.prototype['shortDesc'] = undefined;

/**
 * Brand description
 * @member {String} description
 */
BRANDDETAIL.prototype['description'] = undefined;

/**
 * Array containing a list of Categories codes to which the Brand belongs
 * @member {Array.<Object>} categoryID
 */
BRANDDETAIL.prototype['categoryID'] = undefined;

/**
 * The serial number displays the brand
 * @member {Number} order
 */
BRANDDETAIL.prototype['order'] = undefined;

/**
 * Describe the brand's terms of reference (T&C). HTML format
 * @member {String} serviceGuide
 */
BRANDDETAIL.prototype['serviceGuide'] = undefined;

/**
 * @member {Array.<module:model/STORESSCHEMA>} stores
 */
BRANDDETAIL.prototype['stores'] = undefined;

/**
 * Information on the brand's applicable channels
 * @member {Array.<module:model/USAGEMETHODSCHEMA>} usageMethods
 */
BRANDDETAIL.prototype['usageMethods'] = undefined;






export default BRANDDETAIL;

