/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GROUPVOUCHERSCHEMA model module.
 * @module model/GROUPVOUCHERSCHEMA
 * @version 4.0.0
 */
class GROUPVOUCHERSCHEMA {
    /**
     * Constructs a new <code>GROUPVOUCHERSCHEMA</code>.
     * @alias module:model/GROUPVOUCHERSCHEMA
     */
    constructor() { 
        
        GROUPVOUCHERSCHEMA.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GROUPVOUCHERSCHEMA</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GROUPVOUCHERSCHEMA} obj Optional instance to populate.
     * @return {module:model/GROUPVOUCHERSCHEMA} The populated <code>GROUPVOUCHERSCHEMA</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GROUPVOUCHERSCHEMA();

            if (data.hasOwnProperty('voucherLink')) {
                obj['voucherLink'] = ApiClient.convertToType(data['voucherLink'], 'String');
            }
            if (data.hasOwnProperty('voucherLinkCode')) {
                obj['voucherLinkCode'] = ApiClient.convertToType(data['voucherLinkCode'], 'String');
            }
            if (data.hasOwnProperty('voucherSerial')) {
                obj['voucherSerial'] = ApiClient.convertToType(data['voucherSerial'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GROUPVOUCHERSCHEMA</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GROUPVOUCHERSCHEMA</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['voucherLink'] && !(typeof data['voucherLink'] === 'string' || data['voucherLink'] instanceof String)) {
            throw new Error("Expected the field `voucherLink` to be a primitive type in the JSON string but got " + data['voucherLink']);
        }
        // ensure the json data is a string
        if (data['voucherLinkCode'] && !(typeof data['voucherLinkCode'] === 'string' || data['voucherLinkCode'] instanceof String)) {
            throw new Error("Expected the field `voucherLinkCode` to be a primitive type in the JSON string but got " + data['voucherLinkCode']);
        }
        // ensure the json data is a string
        if (data['voucherSerial'] && !(typeof data['voucherSerial'] === 'string' || data['voucherSerial'] instanceof String)) {
            throw new Error("Expected the field `voucherSerial` to be a primitive type in the JSON string but got " + data['voucherSerial']);
        }

        return true;
    }


}



/**
 * Link of voucher
 * @member {String} voucherLink
 */
GROUPVOUCHERSCHEMA.prototype['voucherLink'] = undefined;

/**
 * Last 8 characters of voucher link
 * @member {String} voucherLinkCode
 */
GROUPVOUCHERSCHEMA.prototype['voucherLinkCode'] = undefined;

/**
 * Is a unique code to identify voucher link v and is not valid for use. For example: V1562342ET2
 * @member {String} voucherSerial
 */
GROUPVOUCHERSCHEMA.prototype['voucherSerial'] = undefined;






export default GROUPVOUCHERSCHEMA;

