/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PRODUCTPRICESCHEMA model module.
 * @module model/PRODUCTPRICESCHEMA
 * @version 4.0.0
 */
class PRODUCTPRICESCHEMA {
    /**
     * Constructs a new <code>PRODUCTPRICESCHEMA</code>.
     * @alias module:model/PRODUCTPRICESCHEMA
     */
    constructor() { 
        
        PRODUCTPRICESCHEMA.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PRODUCTPRICESCHEMA</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PRODUCTPRICESCHEMA} obj Optional instance to populate.
     * @return {module:model/PRODUCTPRICESCHEMA} The populated <code>PRODUCTPRICESCHEMA</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PRODUCTPRICESCHEMA();

            if (data.hasOwnProperty('priceId')) {
                obj['priceId'] = ApiClient.convertToType(data['priceId'], 'Number');
            }
            if (data.hasOwnProperty('priceNm')) {
                obj['priceNm'] = ApiClient.convertToType(data['priceNm'], 'String');
            }
            if (data.hasOwnProperty('priceValue')) {
                obj['priceValue'] = ApiClient.convertToType(data['priceValue'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PRODUCTPRICESCHEMA</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PRODUCTPRICESCHEMA</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['priceNm'] && !(typeof data['priceNm'] === 'string' || data['priceNm'] instanceof String)) {
            throw new Error("Expected the field `priceNm` to be a primitive type in the JSON string but got " + data['priceNm']);
        }

        return true;
    }


}



/**
 * Product id/size code
 * @member {Number} priceId
 */
PRODUCTPRICESCHEMA.prototype['priceId'] = undefined;

/**
 * Product name/size name
 * @member {String} priceNm
 */
PRODUCTPRICESCHEMA.prototype['priceNm'] = undefined;

/**
 * Product value
 * @member {Number} priceValue
 */
PRODUCTPRICESCHEMA.prototype['priceValue'] = undefined;






export default PRODUCTPRICESCHEMA;

