/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VENDORSCHEMA from './VENDORSCHEMA';

/**
 * The PRODUCTG model module.
 * @module model/PRODUCTG
 * @version 4.0.0
 */
class PRODUCTG {
    /**
     * Constructs a new <code>PRODUCTG</code>.
     * @alias module:model/PRODUCTG
     */
    constructor() { 
        
        PRODUCTG.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PRODUCTG</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PRODUCTG} obj Optional instance to populate.
     * @return {module:model/PRODUCTG} The populated <code>PRODUCTG</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PRODUCTG();

            if (data.hasOwnProperty('product_image')) {
                obj['product_image'] = ApiClient.convertToType(data['product_image'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('serial')) {
                obj['serial'] = ApiClient.convertToType(data['serial'], 'String');
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
            }
            if (data.hasOwnProperty('price_id')) {
                obj['price_id'] = ApiClient.convertToType(data['price_id'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('expired_date')) {
                obj['expired_date'] = ApiClient.convertToType(data['expired_date'], 'String');
            }
            if (data.hasOwnProperty('partner')) {
                obj['partner'] = VENDORSCHEMA.constructFromObject(data['partner']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PRODUCTG</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PRODUCTG</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['product_image'] && !(typeof data['product_image'] === 'string' || data['product_image'] instanceof String)) {
            throw new Error("Expected the field `product_image` to be a primitive type in the JSON string but got " + data['product_image']);
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['serial'] && !(typeof data['serial'] === 'string' || data['serial'] instanceof String)) {
            throw new Error("Expected the field `serial` to be a primitive type in the JSON string but got " + data['serial']);
        }
        // ensure the json data is a string
        if (data['expired_date'] && !(typeof data['expired_date'] === 'string' || data['expired_date'] instanceof String)) {
            throw new Error("Expected the field `expired_date` to be a primitive type in the JSON string but got " + data['expired_date']);
        }
        // validate the optional field `partner`
        if (data['partner']) { // data not null
          VENDORSCHEMA.validateJSON(data['partner']);
        }

        return true;
    }


}



/**
 * @member {String} product_image
 */
PRODUCTG.prototype['product_image'] = undefined;

/**
 * @member {String} link
 */
PRODUCTG.prototype['link'] = undefined;

/**
 * @member {String} code
 */
PRODUCTG.prototype['code'] = undefined;

/**
 * @member {String} serial
 */
PRODUCTG.prototype['serial'] = undefined;

/**
 * @member {Number} product_id
 */
PRODUCTG.prototype['product_id'] = undefined;

/**
 * @member {Number} price_id
 */
PRODUCTG.prototype['price_id'] = undefined;

/**
 * @member {Number} value
 */
PRODUCTG.prototype['value'] = undefined;

/**
 * @member {String} expired_date
 */
PRODUCTG.prototype['expired_date'] = undefined;

/**
 * @member {module:model/VENDORSCHEMA} partner
 */
PRODUCTG.prototype['partner'] = undefined;






export default PRODUCTG;

