/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The REQUESTSENDVOUCHERBYSMS model module.
 * @module model/REQUESTSENDVOUCHERBYSMS
 * @version 4.0.0
 */
class REQUESTSENDVOUCHERBYSMS {
    /**
     * Constructs a new <code>REQUESTSENDVOUCHERBYSMS</code>.
     * @alias module:model/REQUESTSENDVOUCHERBYSMS
     * @param voucherLinkCode {String} 
     * @param phoneNo {String} 
     */
    constructor(voucherLinkCode, phoneNo) { 
        
        REQUESTSENDVOUCHERBYSMS.initialize(this, voucherLinkCode, phoneNo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, voucherLinkCode, phoneNo) { 
        obj['voucherLinkCode'] = voucherLinkCode;
        obj['phoneNo'] = phoneNo;
    }

    /**
     * Constructs a <code>REQUESTSENDVOUCHERBYSMS</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/REQUESTSENDVOUCHERBYSMS} obj Optional instance to populate.
     * @return {module:model/REQUESTSENDVOUCHERBYSMS} The populated <code>REQUESTSENDVOUCHERBYSMS</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new REQUESTSENDVOUCHERBYSMS();

            if (data.hasOwnProperty('voucherLinkCode')) {
                obj['voucherLinkCode'] = ApiClient.convertToType(data['voucherLinkCode'], 'String');
            }
            if (data.hasOwnProperty('phoneNo')) {
                obj['phoneNo'] = ApiClient.convertToType(data['phoneNo'], 'String');
            }
            if (data.hasOwnProperty('receiverNm')) {
                obj['receiverNm'] = ApiClient.convertToType(data['receiverNm'], 'String');
            }
            if (data.hasOwnProperty('senderNm')) {
                obj['senderNm'] = ApiClient.convertToType(data['senderNm'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>REQUESTSENDVOUCHERBYSMS</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>REQUESTSENDVOUCHERBYSMS</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of REQUESTSENDVOUCHERBYSMS.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['voucherLinkCode'] && !(typeof data['voucherLinkCode'] === 'string' || data['voucherLinkCode'] instanceof String)) {
            throw new Error("Expected the field `voucherLinkCode` to be a primitive type in the JSON string but got " + data['voucherLinkCode']);
        }
        // ensure the json data is a string
        if (data['phoneNo'] && !(typeof data['phoneNo'] === 'string' || data['phoneNo'] instanceof String)) {
            throw new Error("Expected the field `phoneNo` to be a primitive type in the JSON string but got " + data['phoneNo']);
        }
        // ensure the json data is a string
        if (data['receiverNm'] && !(typeof data['receiverNm'] === 'string' || data['receiverNm'] instanceof String)) {
            throw new Error("Expected the field `receiverNm` to be a primitive type in the JSON string but got " + data['receiverNm']);
        }
        // ensure the json data is a string
        if (data['senderNm'] && !(typeof data['senderNm'] === 'string' || data['senderNm'] instanceof String)) {
            throw new Error("Expected the field `senderNm` to be a primitive type in the JSON string but got " + data['senderNm']);
        }

        return true;
    }


}

REQUESTSENDVOUCHERBYSMS.RequiredProperties = ["voucherLinkCode", "phoneNo"];

/**
 * @member {String} voucherLinkCode
 */
REQUESTSENDVOUCHERBYSMS.prototype['voucherLinkCode'] = undefined;

/**
 * @member {String} phoneNo
 */
REQUESTSENDVOUCHERBYSMS.prototype['phoneNo'] = undefined;

/**
 * @member {String} receiverNm
 */
REQUESTSENDVOUCHERBYSMS.prototype['receiverNm'] = undefined;

/**
 * @member {String} senderNm
 */
REQUESTSENDVOUCHERBYSMS.prototype['senderNm'] = undefined;






export default REQUESTSENDVOUCHERBYSMS;

