/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The REQUESTCHECKSTATUSZNS model module.
 * @module model/REQUESTCHECKSTATUSZNS
 * @version 4.0.0
 */
class REQUESTCHECKSTATUSZNS {
    /**
     * Constructs a new <code>REQUESTCHECKSTATUSZNS</code>.
     * @alias module:model/REQUESTCHECKSTATUSZNS
     */
    constructor() { 
        
        REQUESTCHECKSTATUSZNS.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>REQUESTCHECKSTATUSZNS</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/REQUESTCHECKSTATUSZNS} obj Optional instance to populate.
     * @return {module:model/REQUESTCHECKSTATUSZNS} The populated <code>REQUESTCHECKSTATUSZNS</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new REQUESTCHECKSTATUSZNS();

            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>REQUESTCHECKSTATUSZNS</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>REQUESTCHECKSTATUSZNS</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['transactionId'] && !(typeof data['transactionId'] === 'string' || data['transactionId'] instanceof String)) {
            throw new Error("Expected the field `transactionId` to be a primitive type in the JSON string but got " + data['transactionId']);
        }

        return true;
    }


}



/**
 * @member {String} transactionId
 */
REQUESTCHECKSTATUSZNS.prototype['transactionId'] = undefined;






export default REQUESTCHECKSTATUSZNS;

