/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PRODUCTDEFAULTLINKG from './PRODUCTDEFAULTLINKG';

/**
 * The REQUESTCREATEVOUCHERLINKG model module.
 * @module model/REQUESTCREATEVOUCHERLINKG
 * @version 4.0.0
 */
class REQUESTCREATEVOUCHERLINKG {
    /**
     * Constructs a new <code>REQUESTCREATEVOUCHERLINKG</code>.
     * @alias module:model/REQUESTCREATEVOUCHERLINKG
     * @param productList {Array.<module:model/PRODUCTDEFAULTLINKG>} 
     * @param orderName {String} Please don't use the voucher recipient or the content changes daily or frequently. Owl French: Customers specified name + [Month] + [Year] Example: Got It Promotion - Jul 2019
     * @param expiryDate {String} Voucher expiration date. Syntax 'YYYY-MM-DD'. The expiration date is specified specified in the contract between the partner and Got It, usually 3 months from the release date, maximum 12 months.
     * @param transactionRefId {String} Transaction code receive from the customer request, used for comparison and reconciliation. If the transaction fails, after 5 mintegerues, you can use this transmitted transactionRefID to request again. Maximum 255 characters. Format of transactionRefId: prefix + '_' + character string In which: + prefix: string of 06 integer characters provided by Got It. + character string: string actively generated by clients Example: prefix: '000742' character string: '20220126-6f823f2e' => transactionRefId: '000742_20220126-6f823f2e'
     */
    constructor(productList, orderName, expiryDate, transactionRefId) { 
        
        REQUESTCREATEVOUCHERLINKG.initialize(this, productList, orderName, expiryDate, transactionRefId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productList, orderName, expiryDate, transactionRefId) { 
        obj['productList'] = productList;
        obj['orderName'] = orderName;
        obj['expiryDate'] = expiryDate;
        obj['transactionRefId'] = transactionRefId;
    }

    /**
     * Constructs a <code>REQUESTCREATEVOUCHERLINKG</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/REQUESTCREATEVOUCHERLINKG} obj Optional instance to populate.
     * @return {module:model/REQUESTCREATEVOUCHERLINKG} The populated <code>REQUESTCREATEVOUCHERLINKG</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new REQUESTCREATEVOUCHERLINKG();

            if (data.hasOwnProperty('productList')) {
                obj['productList'] = ApiClient.convertToType(data['productList'], [PRODUCTDEFAULTLINKG]);
            }
            if (data.hasOwnProperty('orderName')) {
                obj['orderName'] = ApiClient.convertToType(data['orderName'], 'String');
            }
            if (data.hasOwnProperty('expiryDate')) {
                obj['expiryDate'] = ApiClient.convertToType(data['expiryDate'], 'String');
            }
            if (data.hasOwnProperty('transactionRefId')) {
                obj['transactionRefId'] = ApiClient.convertToType(data['transactionRefId'], 'String');
            }
            if (data.hasOwnProperty('use_otp')) {
                obj['use_otp'] = ApiClient.convertToType(data['use_otp'], 'Number');
            }
            if (data.hasOwnProperty('otp_type')) {
                obj['otp_type'] = ApiClient.convertToType(data['otp_type'], 'Number');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('receiver_name')) {
                obj['receiver_name'] = ApiClient.convertToType(data['receiver_name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>REQUESTCREATEVOUCHERLINKG</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>REQUESTCREATEVOUCHERLINKG</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of REQUESTCREATEVOUCHERLINKG.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['productList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['productList'])) {
                throw new Error("Expected the field `productList` to be an array in the JSON data but got " + data['productList']);
            }
            // validate the optional field `productList` (array)
            for (const item of data['productList']) {
                PRODUCTDEFAULTLINKG.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['orderName'] && !(typeof data['orderName'] === 'string' || data['orderName'] instanceof String)) {
            throw new Error("Expected the field `orderName` to be a primitive type in the JSON string but got " + data['orderName']);
        }
        // ensure the json data is a string
        if (data['expiryDate'] && !(typeof data['expiryDate'] === 'string' || data['expiryDate'] instanceof String)) {
            throw new Error("Expected the field `expiryDate` to be a primitive type in the JSON string but got " + data['expiryDate']);
        }
        // ensure the json data is a string
        if (data['transactionRefId'] && !(typeof data['transactionRefId'] === 'string' || data['transactionRefId'] instanceof String)) {
            throw new Error("Expected the field `transactionRefId` to be a primitive type in the JSON string but got " + data['transactionRefId']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['receiver_name'] && !(typeof data['receiver_name'] === 'string' || data['receiver_name'] instanceof String)) {
            throw new Error("Expected the field `receiver_name` to be a primitive type in the JSON string but got " + data['receiver_name']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}

REQUESTCREATEVOUCHERLINKG.RequiredProperties = ["productList", "orderName", "expiryDate", "transactionRefId"];

/**
 * @member {Array.<module:model/PRODUCTDEFAULTLINKG>} productList
 */
REQUESTCREATEVOUCHERLINKG.prototype['productList'] = undefined;

/**
 * Please don't use the voucher recipient or the content changes daily or frequently. Owl French: Customers specified name + [Month] + [Year] Example: Got It Promotion - Jul 2019
 * @member {String} orderName
 */
REQUESTCREATEVOUCHERLINKG.prototype['orderName'] = undefined;

/**
 * Voucher expiration date. Syntax 'YYYY-MM-DD'. The expiration date is specified specified in the contract between the partner and Got It, usually 3 months from the release date, maximum 12 months.
 * @member {String} expiryDate
 */
REQUESTCREATEVOUCHERLINKG.prototype['expiryDate'] = undefined;

/**
 * Transaction code receive from the customer request, used for comparison and reconciliation. If the transaction fails, after 5 mintegerues, you can use this transmitted transactionRefID to request again. Maximum 255 characters. Format of transactionRefId: prefix + '_' + character string In which: + prefix: string of 06 integer characters provided by Got It. + character string: string actively generated by clients Example: prefix: '000742' character string: '20220126-6f823f2e' => transactionRefId: '000742_20220126-6f823f2e'
 * @member {String} transactionRefId
 */
REQUESTCREATEVOUCHERLINKG.prototype['transactionRefId'] = undefined;

/**
 * = 1 if the end user is required to enter a password to view the voucher. Example: 1
 * @member {Number} use_otp
 */
REQUESTCREATEVOUCHERLINKG.prototype['use_otp'] = undefined;

/**
 * = 1 if OTP is sent via phone number; = 7 if OTP is sent via email; = 8 if password Password is a fixed number - passed in param 'password' For example: 1
 * @member {Number} otp_type
 */
REQUESTCREATEVOUCHERLINKG.prototype['otp_type'] = undefined;

/**
 * Fixed password (corresponding to otp_type=8 passed in parram 'otp_type'. For otp_type = 1 or 7 do not need to be passed integero this field). Format requirement: 6 consecutive integer characters Example: '325243'
 * @member {String} password
 */
REQUESTCREATEVOUCHERLINKG.prototype['password'] = undefined;

/**
 * Voucher recipient name Example: Son Tran
 * @member {String} receiver_name
 */
REQUESTCREATEVOUCHERLINKG.prototype['receiver_name'] = undefined;

/**
 * Phone number to receive the voucher. This is only the step to identify the phone number that will receive the voucher. This step has not been completed yet. Sending vouchers, sending vouchers via SMS will be a separate API section. This phone number is also used to receive OTP when the end-user opens the voucher link, respectively otp_type = 1. Request format: 10 consecutive integer characters. For example: 0909xxxxxx
 * @member {String} phone
 */
REQUESTCREATEVOUCHERLINKG.prototype['phone'] = undefined;

/**
 * Email to receive the voucher. This is just the step to identify the email address that will receive the voucher. This step does not include sending the voucher, sending the voucher via email will be a separate API section. This email address is also used to receive OTP when the end-user opens the voucher link, corresponding to otp_type = 7 . For example: son.tran@ dayone.vn
 * @member {String} email
 */
REQUESTCREATEVOUCHERLINKG.prototype['email'] = undefined;






export default REQUESTCREATEVOUCHERLINKG;

