/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The REQUESTSENDVOUCHERBYZNS model module.
 * @module model/REQUESTSENDVOUCHERBYZNS
 * @version 4.0.0
 */
class REQUESTSENDVOUCHERBYZNS {
    /**
     * Constructs a new <code>REQUESTSENDVOUCHERBYZNS</code>.
     * @alias module:model/REQUESTSENDVOUCHERBYZNS
     * @param phoneNo {String} 
     * @param voucherSerials {Array.<String>} 
     * @param transactionId {String} 
     */
    constructor(phoneNo, voucherSerials, transactionId) { 
        
        REQUESTSENDVOUCHERBYZNS.initialize(this, phoneNo, voucherSerials, transactionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phoneNo, voucherSerials, transactionId) { 
        obj['phoneNo'] = phoneNo;
        obj['voucherSerials'] = voucherSerials;
        obj['transactionId'] = transactionId;
    }

    /**
     * Constructs a <code>REQUESTSENDVOUCHERBYZNS</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/REQUESTSENDVOUCHERBYZNS} obj Optional instance to populate.
     * @return {module:model/REQUESTSENDVOUCHERBYZNS} The populated <code>REQUESTSENDVOUCHERBYZNS</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new REQUESTSENDVOUCHERBYZNS();

            if (data.hasOwnProperty('phoneNo')) {
                obj['phoneNo'] = ApiClient.convertToType(data['phoneNo'], 'String');
            }
            if (data.hasOwnProperty('receiverNm')) {
                obj['receiverNm'] = ApiClient.convertToType(data['receiverNm'], 'String');
            }
            if (data.hasOwnProperty('voucherSerials')) {
                obj['voucherSerials'] = ApiClient.convertToType(data['voucherSerials'], ['String']);
            }
            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>REQUESTSENDVOUCHERBYZNS</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>REQUESTSENDVOUCHERBYZNS</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of REQUESTSENDVOUCHERBYZNS.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['phoneNo'] && !(typeof data['phoneNo'] === 'string' || data['phoneNo'] instanceof String)) {
            throw new Error("Expected the field `phoneNo` to be a primitive type in the JSON string but got " + data['phoneNo']);
        }
        // ensure the json data is a string
        if (data['receiverNm'] && !(typeof data['receiverNm'] === 'string' || data['receiverNm'] instanceof String)) {
            throw new Error("Expected the field `receiverNm` to be a primitive type in the JSON string but got " + data['receiverNm']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['voucherSerials'])) {
            throw new Error("Expected the field `voucherSerials` to be an array in the JSON data but got " + data['voucherSerials']);
        }
        // ensure the json data is a string
        if (data['transactionId'] && !(typeof data['transactionId'] === 'string' || data['transactionId'] instanceof String)) {
            throw new Error("Expected the field `transactionId` to be a primitive type in the JSON string but got " + data['transactionId']);
        }

        return true;
    }


}

REQUESTSENDVOUCHERBYZNS.RequiredProperties = ["phoneNo", "voucherSerials", "transactionId"];

/**
 * @member {String} phoneNo
 */
REQUESTSENDVOUCHERBYZNS.prototype['phoneNo'] = undefined;

/**
 * @member {String} receiverNm
 */
REQUESTSENDVOUCHERBYZNS.prototype['receiverNm'] = undefined;

/**
 * @member {Array.<String>} voucherSerials
 */
REQUESTSENDVOUCHERBYZNS.prototype['voucherSerials'] = undefined;

/**
 * @member {String} transactionId
 */
REQUESTSENDVOUCHERBYZNS.prototype['transactionId'] = undefined;






export default REQUESTSENDVOUCHERBYZNS;

