/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The REQUESTSENDVOUCHERBYEMAIL model module.
 * @module model/REQUESTSENDVOUCHERBYEMAIL
 * @version 4.0.0
 */
class REQUESTSENDVOUCHERBYEMAIL {
    /**
     * Constructs a new <code>REQUESTSENDVOUCHERBYEMAIL</code>.
     * @alias module:model/REQUESTSENDVOUCHERBYEMAIL
     * @param voucherLinkCode {String} 
     * @param email {String} 
     */
    constructor(voucherLinkCode, email) { 
        
        REQUESTSENDVOUCHERBYEMAIL.initialize(this, voucherLinkCode, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, voucherLinkCode, email) { 
        obj['voucherLinkCode'] = voucherLinkCode;
        obj['email'] = email;
    }

    /**
     * Constructs a <code>REQUESTSENDVOUCHERBYEMAIL</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/REQUESTSENDVOUCHERBYEMAIL} obj Optional instance to populate.
     * @return {module:model/REQUESTSENDVOUCHERBYEMAIL} The populated <code>REQUESTSENDVOUCHERBYEMAIL</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new REQUESTSENDVOUCHERBYEMAIL();

            if (data.hasOwnProperty('voucherLinkCode')) {
                obj['voucherLinkCode'] = ApiClient.convertToType(data['voucherLinkCode'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('receiverNm')) {
                obj['receiverNm'] = ApiClient.convertToType(data['receiverNm'], 'String');
            }
            if (data.hasOwnProperty('senderNm')) {
                obj['senderNm'] = ApiClient.convertToType(data['senderNm'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>REQUESTSENDVOUCHERBYEMAIL</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>REQUESTSENDVOUCHERBYEMAIL</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of REQUESTSENDVOUCHERBYEMAIL.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['voucherLinkCode'] && !(typeof data['voucherLinkCode'] === 'string' || data['voucherLinkCode'] instanceof String)) {
            throw new Error("Expected the field `voucherLinkCode` to be a primitive type in the JSON string but got " + data['voucherLinkCode']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['receiverNm'] && !(typeof data['receiverNm'] === 'string' || data['receiverNm'] instanceof String)) {
            throw new Error("Expected the field `receiverNm` to be a primitive type in the JSON string but got " + data['receiverNm']);
        }
        // ensure the json data is a string
        if (data['senderNm'] && !(typeof data['senderNm'] === 'string' || data['senderNm'] instanceof String)) {
            throw new Error("Expected the field `senderNm` to be a primitive type in the JSON string but got " + data['senderNm']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

REQUESTSENDVOUCHERBYEMAIL.RequiredProperties = ["voucherLinkCode", "email"];

/**
 * @member {String} voucherLinkCode
 */
REQUESTSENDVOUCHERBYEMAIL.prototype['voucherLinkCode'] = undefined;

/**
 * @member {String} email
 */
REQUESTSENDVOUCHERBYEMAIL.prototype['email'] = undefined;

/**
 * @member {String} receiverNm
 */
REQUESTSENDVOUCHERBYEMAIL.prototype['receiverNm'] = undefined;

/**
 * @member {String} senderNm
 */
REQUESTSENDVOUCHERBYEMAIL.prototype['senderNm'] = undefined;

/**
 * @member {String} message
 */
REQUESTSENDVOUCHERBYEMAIL.prototype['message'] = undefined;






export default REQUESTSENDVOUCHERBYEMAIL;

