/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The STOREPAGINGSCHEMA model module.
 * @module model/STOREPAGINGSCHEMA
 * @version 4.0.0
 */
class STOREPAGINGSCHEMA {
    /**
     * Constructs a new <code>STOREPAGINGSCHEMA</code>.
     * @alias module:model/STOREPAGINGSCHEMA
     */
    constructor() { 
        
        STOREPAGINGSCHEMA.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>STOREPAGINGSCHEMA</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/STOREPAGINGSCHEMA} obj Optional instance to populate.
     * @return {module:model/STOREPAGINGSCHEMA} The populated <code>STOREPAGINGSCHEMA</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new STOREPAGINGSCHEMA();

            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
            if (data.hasOwnProperty('totalPage')) {
                obj['totalPage'] = ApiClient.convertToType(data['totalPage'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>STOREPAGINGSCHEMA</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>STOREPAGINGSCHEMA</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Number of page
 * @member {Number} page
 */
STOREPAGINGSCHEMA.prototype['page'] = undefined;

/**
 * Size of page
 * @member {Number} pageSize
 */
STOREPAGINGSCHEMA.prototype['pageSize'] = undefined;

/**
 * Total page
 * @member {Number} totalPage
 */
STOREPAGINGSCHEMA.prototype['totalPage'] = undefined;






export default STOREPAGINGSCHEMA;

