/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VOUCHERESCHEMA from './VOUCHERESCHEMA';

/**
 * The VOUCHERE model module.
 * @module model/VOUCHERE
 * @version 4.0.0
 */
class VOUCHERE {
    /**
     * Constructs a new <code>VOUCHERE</code>.
     * @alias module:model/VOUCHERE
     */
    constructor() { 
        
        VOUCHERE.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VOUCHERE</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VOUCHERE} obj Optional instance to populate.
     * @return {module:model/VOUCHERE} The populated <code>VOUCHERE</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VOUCHERE();

            if (data.hasOwnProperty('transactionRefId')) {
                obj['transactionRefId'] = ApiClient.convertToType(data['transactionRefId'], 'String');
            }
            if (data.hasOwnProperty('vouchers')) {
                obj['vouchers'] = ApiClient.convertToType(data['vouchers'], [VOUCHERESCHEMA]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VOUCHERE</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VOUCHERE</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['transactionRefId'] && !(typeof data['transactionRefId'] === 'string' || data['transactionRefId'] instanceof String)) {
            throw new Error("Expected the field `transactionRefId` to be a primitive type in the JSON string but got " + data['transactionRefId']);
        }
        if (data['vouchers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['vouchers'])) {
                throw new Error("Expected the field `vouchers` to be an array in the JSON data but got " + data['vouchers']);
            }
            // validate the optional field `vouchers` (array)
            for (const item of data['vouchers']) {
                VOUCHERESCHEMA.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * TransactionRefId receive from client request
 * @member {String} transactionRefId
 */
VOUCHERE.prototype['transactionRefId'] = undefined;

/**
 * @member {Array.<module:model/VOUCHERESCHEMA>} vouchers
 */
VOUCHERE.prototype['vouchers'] = undefined;






export default VOUCHERE;

