/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VOUCHERCHECKZNSRESPONSEData model module.
 * @module model/VOUCHERCHECKZNSRESPONSEData
 * @version 4.0.0
 */
class VOUCHERCHECKZNSRESPONSEData {
    /**
     * Constructs a new <code>VOUCHERCHECKZNSRESPONSEData</code>.
     * Response data containing the transactionId
     * @alias module:model/VOUCHERCHECKZNSRESPONSEData
     */
    constructor() { 
        
        VOUCHERCHECKZNSRESPONSEData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VOUCHERCHECKZNSRESPONSEData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VOUCHERCHECKZNSRESPONSEData} obj Optional instance to populate.
     * @return {module:model/VOUCHERCHECKZNSRESPONSEData} The populated <code>VOUCHERCHECKZNSRESPONSEData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VOUCHERCHECKZNSRESPONSEData();

            if (data.hasOwnProperty('serials')) {
                obj['serials'] = ApiClient.convertToType(data['serials'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VOUCHERCHECKZNSRESPONSEData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VOUCHERCHECKZNSRESPONSEData</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} serials
 */
VOUCHERCHECKZNSRESPONSEData.prototype['serials'] = undefined;






export default VOUCHERCHECKZNSRESPONSEData;

