/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VOUCHERESCHEMA model module.
 * @module model/VOUCHERESCHEMA
 * @version 4.0.0
 */
class VOUCHERESCHEMA {
    /**
     * Constructs a new <code>VOUCHERESCHEMA</code>.
     * @alias module:model/VOUCHERESCHEMA
     */
    constructor() { 
        
        VOUCHERESCHEMA.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VOUCHERESCHEMA</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VOUCHERESCHEMA} obj Optional instance to populate.
     * @return {module:model/VOUCHERESCHEMA} The populated <code>VOUCHERESCHEMA</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VOUCHERESCHEMA();

            if (data.hasOwnProperty('voucher_link')) {
                obj['voucher_link'] = ApiClient.convertToType(data['voucher_link'], 'String');
            }
            if (data.hasOwnProperty('voucher_cover_link')) {
                obj['voucher_cover_link'] = ApiClient.convertToType(data['voucher_cover_link'], 'String');
            }
            if (data.hasOwnProperty('voucher_serial')) {
                obj['voucher_serial'] = ApiClient.convertToType(data['voucher_serial'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('expired_date')) {
                obj['expired_date'] = ApiClient.convertToType(data['expired_date'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VOUCHERESCHEMA</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VOUCHERESCHEMA</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['voucher_link'] && !(typeof data['voucher_link'] === 'string' || data['voucher_link'] instanceof String)) {
            throw new Error("Expected the field `voucher_link` to be a primitive type in the JSON string but got " + data['voucher_link']);
        }
        // ensure the json data is a string
        if (data['voucher_cover_link'] && !(typeof data['voucher_cover_link'] === 'string' || data['voucher_cover_link'] instanceof String)) {
            throw new Error("Expected the field `voucher_cover_link` to be a primitive type in the JSON string but got " + data['voucher_cover_link']);
        }
        // ensure the json data is a string
        if (data['voucher_serial'] && !(typeof data['voucher_serial'] === 'string' || data['voucher_serial'] instanceof String)) {
            throw new Error("Expected the field `voucher_serial` to be a primitive type in the JSON string but got " + data['voucher_serial']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['expired_date'] && !(typeof data['expired_date'] === 'string' || data['expired_date'] instanceof String)) {
            throw new Error("Expected the field `expired_date` to be a primitive type in the JSON string but got " + data['expired_date']);
        }

        return true;
    }


}



/**
 * Voucher of link e
 * @member {String} voucher_link
 */
VOUCHERESCHEMA.prototype['voucher_link'] = undefined;

/**
 * Voucher cover of link e
 * @member {String} voucher_cover_link
 */
VOUCHERESCHEMA.prototype['voucher_cover_link'] = undefined;

/**
 * Voucher serial of link e
 * @member {String} voucher_serial
 */
VOUCHERESCHEMA.prototype['voucher_serial'] = undefined;

/**
 * Voucher value of link e
 * @member {String} value
 */
VOUCHERESCHEMA.prototype['value'] = undefined;

/**
 * Expiry date of voucher link Format: 'YYYY-MM-DD'
 * @member {String} expired_date
 */
VOUCHERESCHEMA.prototype['expired_date'] = undefined;






export default VOUCHERESCHEMA;

