/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PRODUCTPRICESCHEMA from './PRODUCTPRICESCHEMA';
import PRODUCTV from './PRODUCTV';

/**
 * The VOUCHERVSCHEMAVouchers model module.
 * @module model/VOUCHERVSCHEMAVouchers
 * @version 4.0.0
 */
class VOUCHERVSCHEMAVouchers {
    /**
     * Constructs a new <code>VOUCHERVSCHEMAVouchers</code>.
     * @alias module:model/VOUCHERVSCHEMAVouchers
     * @implements module:model/PRODUCTV
     */
    constructor() { 
        PRODUCTV.initialize(this);
        VOUCHERVSCHEMAVouchers.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VOUCHERVSCHEMAVouchers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VOUCHERVSCHEMAVouchers} obj Optional instance to populate.
     * @return {module:model/VOUCHERVSCHEMAVouchers} The populated <code>VOUCHERVSCHEMAVouchers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VOUCHERVSCHEMAVouchers();
            PRODUCTV.constructFromObject(data, obj);

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('productNm')) {
                obj['productNm'] = ApiClient.convertToType(data['productNm'], 'String');
            }
            if (data.hasOwnProperty('productImg')) {
                obj['productImg'] = ApiClient.convertToType(data['productImg'], 'String');
            }
            if (data.hasOwnProperty('brandId')) {
                obj['brandId'] = ApiClient.convertToType(data['brandId'], 'Number');
            }
            if (data.hasOwnProperty('brandNm')) {
                obj['brandNm'] = ApiClient.convertToType(data['brandNm'], 'String');
            }
            if (data.hasOwnProperty('brandServiceGuide')) {
                obj['brandServiceGuide'] = ApiClient.convertToType(data['brandServiceGuide'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = PRODUCTPRICESCHEMA.constructFromObject(data['price']);
            }
            if (data.hasOwnProperty('productDesc')) {
                obj['productDesc'] = ApiClient.convertToType(data['productDesc'], 'String');
            }
            if (data.hasOwnProperty('terms')) {
                obj['terms'] = ApiClient.convertToType(data['terms'], 'String');
            }
            if (data.hasOwnProperty('productType')) {
                obj['productType'] = ApiClient.convertToType(data['productType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Product Id
 * @member {Number} productId
 */
VOUCHERVSCHEMAVouchers.prototype['productId'] = undefined;

/**
 * Product Name
 * @member {String} productNm
 */
VOUCHERVSCHEMAVouchers.prototype['productNm'] = undefined;

/**
 * Link product image
 * @member {String} productImg
 */
VOUCHERVSCHEMAVouchers.prototype['productImg'] = undefined;

/**
 * Brand id
 * @member {Number} brandId
 */
VOUCHERVSCHEMAVouchers.prototype['brandId'] = undefined;

/**
 * Brand name
 * @member {String} brandNm
 */
VOUCHERVSCHEMAVouchers.prototype['brandNm'] = undefined;

/**
 * @member {String} brandServiceGuide
 */
VOUCHERVSCHEMAVouchers.prototype['brandServiceGuide'] = undefined;

/**
 * @member {String} link
 */
VOUCHERVSCHEMAVouchers.prototype['link'] = undefined;

/**
 * @member {module:model/PRODUCTPRICESCHEMA} price
 */
VOUCHERVSCHEMAVouchers.prototype['price'] = undefined;

/**
 * @member {String} productDesc
 */
VOUCHERVSCHEMAVouchers.prototype['productDesc'] = undefined;

/**
 * @member {String} terms
 */
VOUCHERVSCHEMAVouchers.prototype['terms'] = undefined;

/**
 * @member {String} productType
 */
VOUCHERVSCHEMAVouchers.prototype['productType'] = undefined;


// Implement PRODUCTV interface:
/**
 * Product Id
 * @member {Number} productId
 */
PRODUCTV.prototype['productId'] = undefined;
/**
 * Product Name
 * @member {String} productNm
 */
PRODUCTV.prototype['productNm'] = undefined;
/**
 * Link product image
 * @member {String} productImg
 */
PRODUCTV.prototype['productImg'] = undefined;
/**
 * Brand id
 * @member {Number} brandId
 */
PRODUCTV.prototype['brandId'] = undefined;
/**
 * Brand name
 * @member {String} brandNm
 */
PRODUCTV.prototype['brandNm'] = undefined;
/**
 * @member {String} brandServiceGuide
 */
PRODUCTV.prototype['brandServiceGuide'] = undefined;
/**
 * @member {String} link
 */
PRODUCTV.prototype['link'] = undefined;
/**
 * @member {module:model/PRODUCTPRICESCHEMA} price
 */
PRODUCTV.prototype['price'] = undefined;
/**
 * @member {String} productDesc
 */
PRODUCTV.prototype['productDesc'] = undefined;
/**
 * @member {String} terms
 */
PRODUCTV.prototype['terms'] = undefined;
/**
 * @member {String} productType
 */
PRODUCTV.prototype['productType'] = undefined;




export default VOUCHERVSCHEMAVouchers;

