/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PRODUCTV from './PRODUCTV';
import STORESSCHEMA from './STORESSCHEMA';

/**
 * The VOUCHERCHECKSCHEMADETAIL model module.
 * @module model/VOUCHERCHECKSCHEMADETAIL
 * @version 4.0.0
 */
class VOUCHERCHECKSCHEMADETAIL {
    /**
     * Constructs a new <code>VOUCHERCHECKSCHEMADETAIL</code>.
     * @alias module:model/VOUCHERCHECKSCHEMADETAIL
     */
    constructor() { 
        
        VOUCHERCHECKSCHEMADETAIL.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VOUCHERCHECKSCHEMADETAIL</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VOUCHERCHECKSCHEMADETAIL} obj Optional instance to populate.
     * @return {module:model/VOUCHERCHECKSCHEMADETAIL} The populated <code>VOUCHERCHECKSCHEMADETAIL</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VOUCHERCHECKSCHEMADETAIL();

            if (data.hasOwnProperty('transactionRefId')) {
                obj['transactionRefId'] = ApiClient.convertToType(data['transactionRefId'], 'String');
            }
            if (data.hasOwnProperty('voucherCode')) {
                obj['voucherCode'] = ApiClient.convertToType(data['voucherCode'], 'String');
            }
            if (data.hasOwnProperty('voucherLink')) {
                obj['voucherLink'] = ApiClient.convertToType(data['voucherLink'], 'String');
            }
            if (data.hasOwnProperty('voucherCoverLink')) {
                obj['voucherCoverLink'] = ApiClient.convertToType(data['voucherCoverLink'], 'String');
            }
            if (data.hasOwnProperty('voucherSerial')) {
                obj['voucherSerial'] = ApiClient.convertToType(data['voucherSerial'], 'String');
            }
            if (data.hasOwnProperty('groupLink')) {
                obj['groupLink'] = ApiClient.convertToType(data['groupLink'], 'String');
            }
            if (data.hasOwnProperty('groupVoucherSerial')) {
                obj['groupVoucherSerial'] = ApiClient.convertToType(data['groupVoucherSerial'], 'String');
            }
            if (data.hasOwnProperty('groupCoverLink')) {
                obj['groupCoverLink'] = ApiClient.convertToType(data['groupCoverLink'], 'String');
            }
            if (data.hasOwnProperty('voucherLinkCode')) {
                obj['voucherLinkCode'] = ApiClient.convertToType(data['voucherLinkCode'], 'String');
            }
            if (data.hasOwnProperty('voucherImageLink')) {
                obj['voucherImageLink'] = ApiClient.convertToType(data['voucherImageLink'], 'String');
            }
            if (data.hasOwnProperty('expiryDate')) {
                obj['expiryDate'] = ApiClient.convertToType(data['expiryDate'], 'String');
            }
            if (data.hasOwnProperty('stateCode')) {
                obj['stateCode'] = ApiClient.convertToType(data['stateCode'], 'Number');
            }
            if (data.hasOwnProperty('stateText')) {
                obj['stateText'] = ApiClient.convertToType(data['stateText'], 'String');
            }
            if (data.hasOwnProperty('used_store')) {
                obj['used_store'] = ApiClient.convertToType(data['used_store'], [STORESSCHEMA]);
            }
            if (data.hasOwnProperty('used_time')) {
                obj['used_time'] = ApiClient.convertToType(data['used_time'], 'String');
            }
            if (data.hasOwnProperty('used_brand')) {
                obj['used_brand'] = ApiClient.convertToType(data['used_brand'], 'String');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = PRODUCTV.constructFromObject(data['product']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VOUCHERCHECKSCHEMADETAIL</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VOUCHERCHECKSCHEMADETAIL</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['transactionRefId'] && !(typeof data['transactionRefId'] === 'string' || data['transactionRefId'] instanceof String)) {
            throw new Error("Expected the field `transactionRefId` to be a primitive type in the JSON string but got " + data['transactionRefId']);
        }
        // ensure the json data is a string
        if (data['voucherCode'] && !(typeof data['voucherCode'] === 'string' || data['voucherCode'] instanceof String)) {
            throw new Error("Expected the field `voucherCode` to be a primitive type in the JSON string but got " + data['voucherCode']);
        }
        // ensure the json data is a string
        if (data['voucherLink'] && !(typeof data['voucherLink'] === 'string' || data['voucherLink'] instanceof String)) {
            throw new Error("Expected the field `voucherLink` to be a primitive type in the JSON string but got " + data['voucherLink']);
        }
        // ensure the json data is a string
        if (data['voucherCoverLink'] && !(typeof data['voucherCoverLink'] === 'string' || data['voucherCoverLink'] instanceof String)) {
            throw new Error("Expected the field `voucherCoverLink` to be a primitive type in the JSON string but got " + data['voucherCoverLink']);
        }
        // ensure the json data is a string
        if (data['voucherSerial'] && !(typeof data['voucherSerial'] === 'string' || data['voucherSerial'] instanceof String)) {
            throw new Error("Expected the field `voucherSerial` to be a primitive type in the JSON string but got " + data['voucherSerial']);
        }
        // ensure the json data is a string
        if (data['groupLink'] && !(typeof data['groupLink'] === 'string' || data['groupLink'] instanceof String)) {
            throw new Error("Expected the field `groupLink` to be a primitive type in the JSON string but got " + data['groupLink']);
        }
        // ensure the json data is a string
        if (data['groupVoucherSerial'] && !(typeof data['groupVoucherSerial'] === 'string' || data['groupVoucherSerial'] instanceof String)) {
            throw new Error("Expected the field `groupVoucherSerial` to be a primitive type in the JSON string but got " + data['groupVoucherSerial']);
        }
        // ensure the json data is a string
        if (data['groupCoverLink'] && !(typeof data['groupCoverLink'] === 'string' || data['groupCoverLink'] instanceof String)) {
            throw new Error("Expected the field `groupCoverLink` to be a primitive type in the JSON string but got " + data['groupCoverLink']);
        }
        // ensure the json data is a string
        if (data['voucherLinkCode'] && !(typeof data['voucherLinkCode'] === 'string' || data['voucherLinkCode'] instanceof String)) {
            throw new Error("Expected the field `voucherLinkCode` to be a primitive type in the JSON string but got " + data['voucherLinkCode']);
        }
        // ensure the json data is a string
        if (data['voucherImageLink'] && !(typeof data['voucherImageLink'] === 'string' || data['voucherImageLink'] instanceof String)) {
            throw new Error("Expected the field `voucherImageLink` to be a primitive type in the JSON string but got " + data['voucherImageLink']);
        }
        // ensure the json data is a string
        if (data['expiryDate'] && !(typeof data['expiryDate'] === 'string' || data['expiryDate'] instanceof String)) {
            throw new Error("Expected the field `expiryDate` to be a primitive type in the JSON string but got " + data['expiryDate']);
        }
        // ensure the json data is a string
        if (data['stateText'] && !(typeof data['stateText'] === 'string' || data['stateText'] instanceof String)) {
            throw new Error("Expected the field `stateText` to be a primitive type in the JSON string but got " + data['stateText']);
        }
        if (data['used_store']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['used_store'])) {
                throw new Error("Expected the field `used_store` to be an array in the JSON data but got " + data['used_store']);
            }
            // validate the optional field `used_store` (array)
            for (const item of data['used_store']) {
                STORESSCHEMA.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['used_time'] && !(typeof data['used_time'] === 'string' || data['used_time'] instanceof String)) {
            throw new Error("Expected the field `used_time` to be a primitive type in the JSON string but got " + data['used_time']);
        }
        // ensure the json data is a string
        if (data['used_brand'] && !(typeof data['used_brand'] === 'string' || data['used_brand'] instanceof String)) {
            throw new Error("Expected the field `used_brand` to be a primitive type in the JSON string but got " + data['used_brand']);
        }
        // validate the optional field `product`
        if (data['product']) { // data not null
          PRODUCTV.validateJSON(data['product']);
        }

        return true;
    }


}



/**
 * TransactionRefId receive from client request
 * @member {String} transactionRefId
 */
VOUCHERCHECKSCHEMADETAIL.prototype['transactionRefId'] = undefined;

/**
 * Voucher code. Contains 10 numbers, unique and not duplicated with any other voucher. For some brands that do not use Got It code but use integerernal code (Big C, Mobile World), the system returns the integerernal code.
 * @member {String} voucherCode
 */
VOUCHERCHECKSCHEMADETAIL.prototype['voucherCode'] = undefined;

/**
 * Link of voucher
 * @member {String} voucherLink
 */
VOUCHERCHECKSCHEMADETAIL.prototype['voucherLink'] = undefined;

/**
 * Cover link of voucher.
 * @member {String} voucherCoverLink
 */
VOUCHERCHECKSCHEMADETAIL.prototype['voucherCoverLink'] = undefined;

/**
 * Is a unique code to identify voucher link v and is not valid for use. For example: V1562342ET2
 * @member {String} voucherSerial
 */
VOUCHERCHECKSCHEMADETAIL.prototype['voucherSerial'] = undefined;

/**
 * https://e-stg.gotit.vn/gLsZaFRN
 * @member {String} groupLink
 */
VOUCHERCHECKSCHEMADETAIL.prototype['groupLink'] = undefined;

/**
 * E2V2RML6F52
 * @member {String} groupVoucherSerial
 */
VOUCHERCHECKSCHEMADETAIL.prototype['groupVoucherSerial'] = undefined;

/**
 * https://e-stg.gotit.vn/gLsZaFRN
 * @member {String} groupCoverLink
 */
VOUCHERCHECKSCHEMADETAIL.prototype['groupCoverLink'] = undefined;

/**
 * Last 8 characters of voucher link
 * @member {String} voucherLinkCode
 */
VOUCHERCHECKSCHEMADETAIL.prototype['voucherLinkCode'] = undefined;

/**
 * Link of voucher image. To display vouchers as images
 * @member {String} voucherImageLink
 */
VOUCHERCHECKSCHEMADETAIL.prototype['voucherImageLink'] = undefined;

/**
 * Voucher expiration date
 * @member {String} expiryDate
 */
VOUCHERCHECKSCHEMADETAIL.prototype['expiryDate'] = undefined;

/**
 * State Code
 * @member {Number} stateCode
 */
VOUCHERCHECKSCHEMADETAIL.prototype['stateCode'] = undefined;

/**
 * State Text
 * @member {String} stateText
 */
VOUCHERCHECKSCHEMADETAIL.prototype['stateText'] = undefined;

/**
 * @member {Array.<module:model/STORESSCHEMA>} used_store
 */
VOUCHERCHECKSCHEMADETAIL.prototype['used_store'] = undefined;

/**
 * Used Time
 * @member {String} used_time
 */
VOUCHERCHECKSCHEMADETAIL.prototype['used_time'] = undefined;

/**
 * State Text
 * @member {String} used_brand
 */
VOUCHERCHECKSCHEMADETAIL.prototype['used_brand'] = undefined;

/**
 * @member {module:model/PRODUCTV} product
 */
VOUCHERCHECKSCHEMADETAIL.prototype['product'] = undefined;






export default VOUCHERCHECKSCHEMADETAIL;

