/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GROUPVOUCHERSCHEMA from './GROUPVOUCHERSCHEMA';
import PRODUCTG from './PRODUCTG';

/**
 * The VOUCHERGSCHEMA model module.
 * @module model/VOUCHERGSCHEMA
 * @version 4.0.0
 */
class VOUCHERGSCHEMA {
    /**
     * Constructs a new <code>VOUCHERGSCHEMA</code>.
     * @alias module:model/VOUCHERGSCHEMA
     */
    constructor() { 
        
        VOUCHERGSCHEMA.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VOUCHERGSCHEMA</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VOUCHERGSCHEMA} obj Optional instance to populate.
     * @return {module:model/VOUCHERGSCHEMA} The populated <code>VOUCHERGSCHEMA</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VOUCHERGSCHEMA();

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
            }
            if (data.hasOwnProperty('orderName')) {
                obj['orderName'] = ApiClient.convertToType(data['orderName'], 'String');
            }
            if (data.hasOwnProperty('groupVouchers')) {
                obj['groupVouchers'] = GROUPVOUCHERSCHEMA.constructFromObject(data['groupVouchers']);
            }
            if (data.hasOwnProperty('vouchers')) {
                obj['vouchers'] = ApiClient.convertToType(data['vouchers'], [PRODUCTG]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VOUCHERGSCHEMA</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VOUCHERGSCHEMA</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['orderName'] && !(typeof data['orderName'] === 'string' || data['orderName'] instanceof String)) {
            throw new Error("Expected the field `orderName` to be a primitive type in the JSON string but got " + data['orderName']);
        }
        // validate the optional field `groupVouchers`
        if (data['groupVouchers']) { // data not null
          GROUPVOUCHERSCHEMA.validateJSON(data['groupVouchers']);
        }
        if (data['vouchers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['vouchers'])) {
                throw new Error("Expected the field `vouchers` to be an array in the JSON data but got " + data['vouchers']);
            }
            // validate the optional field `vouchers` (array)
            for (const item of data['vouchers']) {
                PRODUCTG.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Order Id
 * @member {Number} orderId
 */
VOUCHERGSCHEMA.prototype['orderId'] = undefined;

/**
 * Order name from client request
 * @member {String} orderName
 */
VOUCHERGSCHEMA.prototype['orderName'] = undefined;

/**
 * @member {module:model/GROUPVOUCHERSCHEMA} groupVouchers
 */
VOUCHERGSCHEMA.prototype['groupVouchers'] = undefined;

/**
 * @member {Array.<module:model/PRODUCTG>} vouchers
 */
VOUCHERGSCHEMA.prototype['vouchers'] = undefined;






export default VOUCHERGSCHEMA;

