/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VOUCHERSENDSMSSCHEMA model module.
 * @module model/VOUCHERSENDSMSSCHEMA
 * @version 4.0.0
 */
class VOUCHERSENDSMSSCHEMA {
    /**
     * Constructs a new <code>VOUCHERSENDSMSSCHEMA</code>.
     * @alias module:model/VOUCHERSENDSMSSCHEMA
     */
    constructor() { 
        
        VOUCHERSENDSMSSCHEMA.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VOUCHERSENDSMSSCHEMA</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VOUCHERSENDSMSSCHEMA} obj Optional instance to populate.
     * @return {module:model/VOUCHERSENDSMSSCHEMA} The populated <code>VOUCHERSENDSMSSCHEMA</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VOUCHERSENDSMSSCHEMA();

            if (data.hasOwnProperty('voucherLinkCode')) {
                obj['voucherLinkCode'] = ApiClient.convertToType(data['voucherLinkCode'], 'String');
            }
            if (data.hasOwnProperty('phoneNo')) {
                obj['phoneNo'] = ApiClient.convertToType(data['phoneNo'], 'String');
            }
            if (data.hasOwnProperty('receiverNm')) {
                obj['receiverNm'] = ApiClient.convertToType(data['receiverNm'], 'String');
            }
            if (data.hasOwnProperty('senderNm')) {
                obj['senderNm'] = ApiClient.convertToType(data['senderNm'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VOUCHERSENDSMSSCHEMA</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VOUCHERSENDSMSSCHEMA</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['voucherLinkCode'] && !(typeof data['voucherLinkCode'] === 'string' || data['voucherLinkCode'] instanceof String)) {
            throw new Error("Expected the field `voucherLinkCode` to be a primitive type in the JSON string but got " + data['voucherLinkCode']);
        }
        // ensure the json data is a string
        if (data['phoneNo'] && !(typeof data['phoneNo'] === 'string' || data['phoneNo'] instanceof String)) {
            throw new Error("Expected the field `phoneNo` to be a primitive type in the JSON string but got " + data['phoneNo']);
        }
        // ensure the json data is a string
        if (data['receiverNm'] && !(typeof data['receiverNm'] === 'string' || data['receiverNm'] instanceof String)) {
            throw new Error("Expected the field `receiverNm` to be a primitive type in the JSON string but got " + data['receiverNm']);
        }
        // ensure the json data is a string
        if (data['senderNm'] && !(typeof data['senderNm'] === 'string' || data['senderNm'] instanceof String)) {
            throw new Error("Expected the field `senderNm` to be a primitive type in the JSON string but got " + data['senderNm']);
        }

        return true;
    }


}



/**
 * Last 8 characters of voucher link
 * @member {String} voucherLinkCode
 */
VOUCHERSENDSMSSCHEMA.prototype['voucherLinkCode'] = undefined;

/**
 * Phone of user receive voucher
 * @member {String} phoneNo
 */
VOUCHERSENDSMSSCHEMA.prototype['phoneNo'] = undefined;

/**
 * Email of user receive voucher
 * @member {String} receiverNm
 */
VOUCHERSENDSMSSCHEMA.prototype['receiverNm'] = undefined;

/**
 * Name of sender
 * @member {String} senderNm
 */
VOUCHERSENDSMSSCHEMA.prototype['senderNm'] = undefined;






export default VOUCHERSENDSMSSCHEMA;

