/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CATEGORIESRESPONSE from '../model/CATEGORIESRESPONSE';
import HTTPBADREQUEST from '../model/HTTPBADREQUEST';
import HTTPINTERNALSERVERERROR from '../model/HTTPINTERNALSERVERERROR';
import HTTPNOTFOUND from '../model/HTTPNOTFOUND';
import HTTPUNAUTHORIZED from '../model/HTTPUNAUTHORIZED';

/**
* Categories service.
* @module api/CategoriesApi
* @version 4.0.0
*/
export default class CategoriesApi {

    /**
    * Constructs a new CategoriesApi. 
    * @alias module:api/CategoriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCategoryByProduct operation.
     * @callback module:api/CategoriesApi~getCategoryByProductCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CATEGORIESRESPONSE} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get category by product
     * Returns all categories data master
     * @param {String} xGIAuthorization Authorization
     * @param {module:api/CategoriesApi~getCategoryByProductCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CATEGORIESRESPONSE}
     */
    getCategoryByProduct(xGIAuthorization, callback) {
      let postBody = null;
      // verify the required parameter 'xGIAuthorization' is set
      if (xGIAuthorization === undefined || xGIAuthorization === null) {
        throw new Error("Missing the required parameter 'xGIAuthorization' when calling getCategoryByProduct");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-GI-Authorization': xGIAuthorization
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CATEGORIESRESPONSE;
      return this.apiClient.callApi(
        '/api/v4.0/categories/categoriesByProducts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getListOfCategories operation.
     * @callback module:api/CategoriesApi~getListOfCategoriesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CATEGORIESRESPONSE} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get lists category
     * Returns all categories data master
     * @param {String} xGIAuthorization Authorization
     * @param {module:api/CategoriesApi~getListOfCategoriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CATEGORIESRESPONSE}
     */
    getListOfCategories(xGIAuthorization, callback) {
      let postBody = null;
      // verify the required parameter 'xGIAuthorization' is set
      if (xGIAuthorization === undefined || xGIAuthorization === null) {
        throw new Error("Missing the required parameter 'xGIAuthorization' when calling getListOfCategories");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-GI-Authorization': xGIAuthorization
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CATEGORIESRESPONSE;
      return this.apiClient.callApi(
        '/api/v4.0/categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
