/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPBADREQUEST from '../model/HTTPBADREQUEST';
import HTTPINTERNALSERVERERROR from '../model/HTTPINTERNALSERVERERROR';
import HTTPNOTFOUND from '../model/HTTPNOTFOUND';
import HTTPUNAUTHORIZED from '../model/HTTPUNAUTHORIZED';
import VOUCHERCHECKRESPONSE from '../model/VOUCHERCHECKRESPONSE';

/**
* VoucherStatus service.
* @module api/VoucherStatusApi
* @version 4.0.0
*/
export default class VoucherStatusApi {

    /**
    * Constructs a new VoucherStatusApi. 
    * @alias module:api/VoucherStatusApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the checkVoucher operation.
     * @callback module:api/VoucherStatusApi~checkVoucherCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VOUCHERCHECKRESPONSE} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check voucher status
     * Check voucher status
     * @param {String} xGIAuthorization Authorization
     * @param {String} refId Transaction RefId
     * @param {Object} opts Optional parameters
     * @param {Boolean} [isExcludeStoreListInfo] Exclude store list information
     * @param {Number} [storeListPage] Store Page
     * @param {Number} [storeListPageSize] Store Page Size
     * @param {module:api/VoucherStatusApi~checkVoucherCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VOUCHERCHECKRESPONSE}
     */
    checkVoucher(xGIAuthorization, refId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xGIAuthorization' is set
      if (xGIAuthorization === undefined || xGIAuthorization === null) {
        throw new Error("Missing the required parameter 'xGIAuthorization' when calling checkVoucher");
      }
      // verify the required parameter 'refId' is set
      if (refId === undefined || refId === null) {
        throw new Error("Missing the required parameter 'refId' when calling checkVoucher");
      }

      let pathParams = {
        'refId': refId
      };
      let queryParams = {
        'isExcludeStoreListInfo': opts['isExcludeStoreListInfo'],
        'storeListPage': opts['storeListPage'],
        'storeListPageSize': opts['storeListPageSize']
      };
      let headerParams = {
        'X-GI-Authorization': xGIAuthorization
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = VOUCHERCHECKRESPONSE;
      return this.apiClient.callApi(
        '/api/v4.0/vouchers/multiple/status/{refId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
