/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApi);
  }
}(this, function(expect, SampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApi.BRANDREEDEMSCHEMA();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BRANDREEDEMSCHEMA', function() {
    it('should create an instance of BRANDREEDEMSCHEMA', function() {
      // uncomment below and update the code to test BRANDREEDEMSCHEMA
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be.a(SampleApi.BRANDREEDEMSCHEMA);
    });

    it('should have the property brandID (base name: "brandID")', function() {
      // uncomment below and update the code to test the property brandID
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property brandName (base name: "brandName")', function() {
      // uncomment below and update the code to test the property brandName
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property brandLogo (base name: "brandLogo")', function() {
      // uncomment below and update the code to test the property brandLogo
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property brandNameSlug (base name: "brandNameSlug")', function() {
      // uncomment below and update the code to test the property brandNameSlug
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property brandPhone (base name: "brandPhone")', function() {
      // uncomment below and update the code to test the property brandPhone
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property brandAddress (base name: "brandAddress")', function() {
      // uncomment below and update the code to test the property brandAddress
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property brandDesc (base name: "brandDesc")', function() {
      // uncomment below and update the code to test the property brandDesc
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property brandServiceGuide (base name: "brandServiceGuide")', function() {
      // uncomment below and update the code to test the property brandServiceGuide
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property categoryId (base name: "categoryId")', function() {
      // uncomment below and update the code to test the property categoryId
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property categoryNm (base name: "categoryNm")', function() {
      // uncomment below and update the code to test the property categoryNm
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property categoryImg (base name: "categoryImg")', function() {
      // uncomment below and update the code to test the property categoryImg
      //var instance = new SampleApi.BRANDREEDEMSCHEMA();
      //expect(instance).to.be();
    });

  });

}));
