/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApi);
  }
}(this, function(expect, SampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApi.BRANDSDETAIL();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BRANDSDETAIL', function() {
    it('should create an instance of BRANDSDETAIL', function() {
      // uncomment below and update the code to test BRANDSDETAIL
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be.a(SampleApi.BRANDSDETAIL);
    });

    it('should have the property brandId (base name: "brandId")', function() {
      // uncomment below and update the code to test the property brandId
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property brandNm (base name: "brandNm")', function() {
      // uncomment below and update the code to test the property brandNm
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property brandLogo (base name: "brandLogo")', function() {
      // uncomment below and update the code to test the property brandLogo
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property shortDesc (base name: "shortDesc")', function() {
      // uncomment below and update the code to test the property shortDesc
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property categoryID (base name: "categoryID")', function() {
      // uncomment below and update the code to test the property categoryID
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property order (base name: "order")', function() {
      // uncomment below and update the code to test the property order
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property serviceGuide (base name: "serviceGuide")', function() {
      // uncomment below and update the code to test the property serviceGuide
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

    it('should have the property usageMethods (base name: "usageMethods")', function() {
      // uncomment below and update the code to test the property usageMethods
      //var instance = new SampleApi.BRANDSDETAIL();
      //expect(instance).to.be();
    });

  });

}));
