/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApi);
  }
}(this, function(expect, SampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApi.PRODUCTV();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PRODUCTV', function() {
    it('should create an instance of PRODUCTV', function() {
      // uncomment below and update the code to test PRODUCTV
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be.a(SampleApi.PRODUCTV);
    });

    it('should have the property productId (base name: "productId")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property productNm (base name: "productNm")', function() {
      // uncomment below and update the code to test the property productNm
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property productImg (base name: "productImg")', function() {
      // uncomment below and update the code to test the property productImg
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property brandId (base name: "brandId")', function() {
      // uncomment below and update the code to test the property brandId
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property brandNm (base name: "brandNm")', function() {
      // uncomment below and update the code to test the property brandNm
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property brandServiceGuide (base name: "brandServiceGuide")', function() {
      // uncomment below and update the code to test the property brandServiceGuide
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property productDesc (base name: "productDesc")', function() {
      // uncomment below and update the code to test the property productDesc
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property terms (base name: "terms")', function() {
      // uncomment below and update the code to test the property terms
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

    it('should have the property productType (base name: "productType")', function() {
      // uncomment below and update the code to test the property productType
      //var instance = new SampleApi.PRODUCTV();
      //expect(instance).to.be();
    });

  });

}));
