/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApi);
  }
}(this, function(expect, SampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApi.PRODUCTSDEFAULTLINKG();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PRODUCTSDEFAULTLINKG', function() {
    it('should create an instance of PRODUCTSDEFAULTLINKG', function() {
      // uncomment below and update the code to test PRODUCTSDEFAULTLINKG
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be.a(SampleApi.PRODUCTSDEFAULTLINKG);
    });

    it('should have the property productImage (base name: "product_image")', function() {
      // uncomment below and update the code to test the property productImage
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be();
    });

    it('should have the property serial (base name: "serial")', function() {
      // uncomment below and update the code to test the property serial
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "product_id")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be();
    });

    it('should have the property priceId (base name: "price_id")', function() {
      // uncomment below and update the code to test the property priceId
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be();
    });

    it('should have the property expiredDate (base name: "expired_date")', function() {
      // uncomment below and update the code to test the property expiredDate
      //var instance = new SampleApi.PRODUCTSDEFAULTLINKG();
      //expect(instance).to.be();
    });

  });

}));
