/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApi);
  }
}(this, function(expect, SampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApi.REQUESTSENDVOUCHERBYZNS();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('REQUESTSENDVOUCHERBYZNS', function() {
    it('should create an instance of REQUESTSENDVOUCHERBYZNS', function() {
      // uncomment below and update the code to test REQUESTSENDVOUCHERBYZNS
      //var instance = new SampleApi.REQUESTSENDVOUCHERBYZNS();
      //expect(instance).to.be.a(SampleApi.REQUESTSENDVOUCHERBYZNS);
    });

    it('should have the property phoneNo (base name: "phoneNo")', function() {
      // uncomment below and update the code to test the property phoneNo
      //var instance = new SampleApi.REQUESTSENDVOUCHERBYZNS();
      //expect(instance).to.be();
    });

    it('should have the property receiverNm (base name: "receiverNm")', function() {
      // uncomment below and update the code to test the property receiverNm
      //var instance = new SampleApi.REQUESTSENDVOUCHERBYZNS();
      //expect(instance).to.be();
    });

    it('should have the property voucherSerials (base name: "voucherSerials")', function() {
      // uncomment below and update the code to test the property voucherSerials
      //var instance = new SampleApi.REQUESTSENDVOUCHERBYZNS();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transactionId")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new SampleApi.REQUESTSENDVOUCHERBYZNS();
      //expect(instance).to.be();
    });

  });

}));
