/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApi);
  }
}(this, function(expect, SampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('REQUESTCREATEVOUCHERLINKG', function() {
    it('should create an instance of REQUESTCREATEVOUCHERLINKG', function() {
      // uncomment below and update the code to test REQUESTCREATEVOUCHERLINKG
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be.a(SampleApi.REQUESTCREATEVOUCHERLINKG);
    });

    it('should have the property productList (base name: "productList")', function() {
      // uncomment below and update the code to test the property productList
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property orderName (base name: "orderName")', function() {
      // uncomment below and update the code to test the property orderName
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property expiryDate (base name: "expiryDate")', function() {
      // uncomment below and update the code to test the property expiryDate
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property transactionRefId (base name: "transactionRefId")', function() {
      // uncomment below and update the code to test the property transactionRefId
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property useOtp (base name: "use_otp")', function() {
      // uncomment below and update the code to test the property useOtp
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property otpType (base name: "otp_type")', function() {
      // uncomment below and update the code to test the property otpType
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property receiverName (base name: "receiver_name")', function() {
      // uncomment below and update the code to test the property receiverName
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new SampleApi.REQUESTCREATEVOUCHERLINKG();
      //expect(instance).to.be();
    });

  });

}));
