/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApi);
  }
}(this, function(expect, SampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApi.STOREPRODUCTSCHEMA();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('STOREPRODUCTSCHEMA', function() {
    it('should create an instance of STOREPRODUCTSCHEMA', function() {
      // uncomment below and update the code to test STOREPRODUCTSCHEMA
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be.a(SampleApi.STOREPRODUCTSCHEMA);
    });

    it('should have the property storeId (base name: "storeId")', function() {
      // uncomment below and update the code to test the property storeId
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property storeNm (base name: "storeNm")', function() {
      // uncomment below and update the code to test the property storeNm
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property storeAddr (base name: "storeAddr")', function() {
      // uncomment below and update the code to test the property storeAddr
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property lat (base name: "lat")', function() {
      // uncomment below and update the code to test the property lat
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property _long (base name: "long")', function() {
      // uncomment below and update the code to test the property _long
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property cityId (base name: "city_id")', function() {
      // uncomment below and update the code to test the property cityId
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property distId (base name: "dist_id")', function() {
      // uncomment below and update the code to test the property distId
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

    it('should have the property district (base name: "district")', function() {
      // uncomment below and update the code to test the property district
      //var instance = new SampleApi.STOREPRODUCTSCHEMA();
      //expect(instance).to.be();
    });

  });

}));
