/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SampleApi);
  }
}(this, function(expect, SampleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VOUCHERCHECKSCHEMADETAIL', function() {
    it('should create an instance of VOUCHERCHECKSCHEMADETAIL', function() {
      // uncomment below and update the code to test VOUCHERCHECKSCHEMADETAIL
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be.a(SampleApi.VOUCHERCHECKSCHEMADETAIL);
    });

    it('should have the property transactionRefId (base name: "transactionRefId")', function() {
      // uncomment below and update the code to test the property transactionRefId
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property voucherCode (base name: "voucherCode")', function() {
      // uncomment below and update the code to test the property voucherCode
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property voucherLink (base name: "voucherLink")', function() {
      // uncomment below and update the code to test the property voucherLink
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property voucherCoverLink (base name: "voucherCoverLink")', function() {
      // uncomment below and update the code to test the property voucherCoverLink
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property voucherSerial (base name: "voucherSerial")', function() {
      // uncomment below and update the code to test the property voucherSerial
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property groupLink (base name: "groupLink")', function() {
      // uncomment below and update the code to test the property groupLink
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property groupVoucherSerial (base name: "groupVoucherSerial")', function() {
      // uncomment below and update the code to test the property groupVoucherSerial
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property groupCoverLink (base name: "groupCoverLink")', function() {
      // uncomment below and update the code to test the property groupCoverLink
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property voucherLinkCode (base name: "voucherLinkCode")', function() {
      // uncomment below and update the code to test the property voucherLinkCode
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property voucherImageLink (base name: "voucherImageLink")', function() {
      // uncomment below and update the code to test the property voucherImageLink
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property expiryDate (base name: "expiryDate")', function() {
      // uncomment below and update the code to test the property expiryDate
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property stateCode (base name: "stateCode")', function() {
      // uncomment below and update the code to test the property stateCode
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property stateText (base name: "stateText")', function() {
      // uncomment below and update the code to test the property stateText
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property usedStore (base name: "used_store")', function() {
      // uncomment below and update the code to test the property usedStore
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property usedTime (base name: "used_time")', function() {
      // uncomment below and update the code to test the property usedTime
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property usedBrand (base name: "used_brand")', function() {
      // uncomment below and update the code to test the property usedBrand
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

    it('should have the property product (base name: "product")', function() {
      // uncomment below and update the code to test the property product
      //var instance = new SampleApi.VOUCHERCHECKSCHEMADETAIL();
      //expect(instance).to.be();
    });

  });

}));
