/**
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BRANDCATEGORYDETAIL from './model/BRANDCATEGORYDETAIL';
import BRANDCATEGORYDETAILRESPONSE from './model/BRANDCATEGORYDETAILRESPONSE';
import BRANDDETAIL from './model/BRANDDETAIL';
import BRANDDETAILRESPONSE from './model/BRANDDETAILRESPONSE';
import BRANDREEDEMSCHEMA from './model/BRANDREEDEMSCHEMA';
import BRANDSDETAIL from './model/BRANDSDETAIL';
import BRANDSRESPONSE from './model/BRANDSRESPONSE';
import CATEGORIESDETAIL from './model/CATEGORIESDETAIL';
import CATEGORIESRESPONSE from './model/CATEGORIESRESPONSE';
import GROUPVOUCHERSCHEMA from './model/GROUPVOUCHERSCHEMA';
import HTTPBADREQUEST from './model/HTTPBADREQUEST';
import HTTPINTERNALSERVERERROR from './model/HTTPINTERNALSERVERERROR';
import HTTPNOTFOUND from './model/HTTPNOTFOUND';
import HTTPUNAUTHORIZED from './model/HTTPUNAUTHORIZED';
import PAGINGSCHEMA from './model/PAGINGSCHEMA';
import PRODUCTDEFAULTLINKG from './model/PRODUCTDEFAULTLINKG';
import PRODUCTDETAIL from './model/PRODUCTDETAIL';
import PRODUCTDETAILRESPONSE from './model/PRODUCTDETAILRESPONSE';
import PRODUCTG from './model/PRODUCTG';
import PRODUCTPRICESCHEMA from './model/PRODUCTPRICESCHEMA';
import PRODUCTSALLDETAIL from './model/PRODUCTSALLDETAIL';
import PRODUCTSDEFAULTLINKG from './model/PRODUCTSDEFAULTLINKG';
import PRODUCTSDETAIL from './model/PRODUCTSDETAIL';
import PRODUCTSRESPONSE from './model/PRODUCTSRESPONSE';
import PRODUCTSRESPONSEDataInner from './model/PRODUCTSRESPONSEDataInner';
import PRODUCTSVOUCHERCHECK from './model/PRODUCTSVOUCHERCHECK';
import PRODUCTV from './model/PRODUCTV';
import PRODUCTVENDORLINKG from './model/PRODUCTVENDORLINKG';
import REQUESTCHECKSTATUSZNS from './model/REQUESTCHECKSTATUSZNS';
import REQUESTCREATEVOUCHERLINKE from './model/REQUESTCREATEVOUCHERLINKE';
import REQUESTCREATEVOUCHERLINKG from './model/REQUESTCREATEVOUCHERLINKG';
import REQUESTCREATEVOUCHERLINKV from './model/REQUESTCREATEVOUCHERLINKV';
import REQUESTSENDVOUCHERBYEMAIL from './model/REQUESTSENDVOUCHERBYEMAIL';
import REQUESTSENDVOUCHERBYSMS from './model/REQUESTSENDVOUCHERBYSMS';
import REQUESTSENDVOUCHERBYZNS from './model/REQUESTSENDVOUCHERBYZNS';
import STOREPAGINGSCHEMA from './model/STOREPAGINGSCHEMA';
import STOREPRODUCTSCHEMA from './model/STOREPRODUCTSCHEMA';
import STORESRESPONSE from './model/STORESRESPONSE';
import STORESRESPONSEDataInner from './model/STORESRESPONSEDataInner';
import STORESSCHEMA from './model/STORESSCHEMA';
import USAGEMETHODSCHEMA from './model/USAGEMETHODSCHEMA';
import VENDORSCHEMA from './model/VENDORSCHEMA';
import VOUCHERCHECKRESPONSE from './model/VOUCHERCHECKRESPONSE';
import VOUCHERCHECKSCHEMA from './model/VOUCHERCHECKSCHEMA';
import VOUCHERCHECKSCHEMADETAIL from './model/VOUCHERCHECKSCHEMADETAIL';
import VOUCHERCHECKZNSRESPONSE from './model/VOUCHERCHECKZNSRESPONSE';
import VOUCHERCHECKZNSRESPONSEData from './model/VOUCHERCHECKZNSRESPONSEData';
import VOUCHERE from './model/VOUCHERE';
import VOUCHERERESPONSE from './model/VOUCHERERESPONSE';
import VOUCHERESCHEMA from './model/VOUCHERESCHEMA';
import VOUCHERG from './model/VOUCHERG';
import VOUCHERGRESPONSE from './model/VOUCHERGRESPONSE';
import VOUCHERGSCHEMA from './model/VOUCHERGSCHEMA';
import VOUCHERSENDEMAILRESPONSE from './model/VOUCHERSENDEMAILRESPONSE';
import VOUCHERSENDEMAILSCHEMA from './model/VOUCHERSENDEMAILSCHEMA';
import VOUCHERSENDSMSRESPONSE from './model/VOUCHERSENDSMSRESPONSE';
import VOUCHERSENDSMSSCHEMA from './model/VOUCHERSENDSMSSCHEMA';
import VOUCHERSENDZNSRESPONSE from './model/VOUCHERSENDZNSRESPONSE';
import VOUCHERSENDZNSRESPONSEData from './model/VOUCHERSENDZNSRESPONSEData';
import VOUCHERV from './model/VOUCHERV';
import VOUCHERVRESPONSE from './model/VOUCHERVRESPONSE';
import VOUCHERVSCHEMA from './model/VOUCHERVSCHEMA';
import VOUCHERVSCHEMAProduct from './model/VOUCHERVSCHEMAProduct';
import BrandsApi from './api/BrandsApi';
import CategoriesApi from './api/CategoriesApi';
import ProductsApi from './api/ProductsApi';
import VoucherApi from './api/VoucherApi';
import VoucherSendMethodApi from './api/VoucherSendMethodApi';
import VoucherStatusApi from './api/VoucherStatusApi';


/**
* Technical document APIs for API Version 4..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GotitApiJavascriptSdk = require('index'); // See note below*.
* var xxxSvc = new GotitApiJavascriptSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GotitApiJavascriptSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GotitApiJavascriptSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GotitApiJavascriptSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 4.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BRANDCATEGORYDETAIL model constructor.
     * @property {module:model/BRANDCATEGORYDETAIL}
     */
    BRANDCATEGORYDETAIL,

    /**
     * The BRANDCATEGORYDETAILRESPONSE model constructor.
     * @property {module:model/BRANDCATEGORYDETAILRESPONSE}
     */
    BRANDCATEGORYDETAILRESPONSE,

    /**
     * The BRANDDETAIL model constructor.
     * @property {module:model/BRANDDETAIL}
     */
    BRANDDETAIL,

    /**
     * The BRANDDETAILRESPONSE model constructor.
     * @property {module:model/BRANDDETAILRESPONSE}
     */
    BRANDDETAILRESPONSE,

    /**
     * The BRANDREEDEMSCHEMA model constructor.
     * @property {module:model/BRANDREEDEMSCHEMA}
     */
    BRANDREEDEMSCHEMA,

    /**
     * The BRANDSDETAIL model constructor.
     * @property {module:model/BRANDSDETAIL}
     */
    BRANDSDETAIL,

    /**
     * The BRANDSRESPONSE model constructor.
     * @property {module:model/BRANDSRESPONSE}
     */
    BRANDSRESPONSE,

    /**
     * The CATEGORIESDETAIL model constructor.
     * @property {module:model/CATEGORIESDETAIL}
     */
    CATEGORIESDETAIL,

    /**
     * The CATEGORIESRESPONSE model constructor.
     * @property {module:model/CATEGORIESRESPONSE}
     */
    CATEGORIESRESPONSE,

    /**
     * The GROUPVOUCHERSCHEMA model constructor.
     * @property {module:model/GROUPVOUCHERSCHEMA}
     */
    GROUPVOUCHERSCHEMA,

    /**
     * The HTTPBADREQUEST model constructor.
     * @property {module:model/HTTPBADREQUEST}
     */
    HTTPBADREQUEST,

    /**
     * The HTTPINTERNALSERVERERROR model constructor.
     * @property {module:model/HTTPINTERNALSERVERERROR}
     */
    HTTPINTERNALSERVERERROR,

    /**
     * The HTTPNOTFOUND model constructor.
     * @property {module:model/HTTPNOTFOUND}
     */
    HTTPNOTFOUND,

    /**
     * The HTTPUNAUTHORIZED model constructor.
     * @property {module:model/HTTPUNAUTHORIZED}
     */
    HTTPUNAUTHORIZED,

    /**
     * The PAGINGSCHEMA model constructor.
     * @property {module:model/PAGINGSCHEMA}
     */
    PAGINGSCHEMA,

    /**
     * The PRODUCTDEFAULTLINKG model constructor.
     * @property {module:model/PRODUCTDEFAULTLINKG}
     */
    PRODUCTDEFAULTLINKG,

    /**
     * The PRODUCTDETAIL model constructor.
     * @property {module:model/PRODUCTDETAIL}
     */
    PRODUCTDETAIL,

    /**
     * The PRODUCTDETAILRESPONSE model constructor.
     * @property {module:model/PRODUCTDETAILRESPONSE}
     */
    PRODUCTDETAILRESPONSE,

    /**
     * The PRODUCTG model constructor.
     * @property {module:model/PRODUCTG}
     */
    PRODUCTG,

    /**
     * The PRODUCTPRICESCHEMA model constructor.
     * @property {module:model/PRODUCTPRICESCHEMA}
     */
    PRODUCTPRICESCHEMA,

    /**
     * The PRODUCTSALLDETAIL model constructor.
     * @property {module:model/PRODUCTSALLDETAIL}
     */
    PRODUCTSALLDETAIL,

    /**
     * The PRODUCTSDEFAULTLINKG model constructor.
     * @property {module:model/PRODUCTSDEFAULTLINKG}
     */
    PRODUCTSDEFAULTLINKG,

    /**
     * The PRODUCTSDETAIL model constructor.
     * @property {module:model/PRODUCTSDETAIL}
     */
    PRODUCTSDETAIL,

    /**
     * The PRODUCTSRESPONSE model constructor.
     * @property {module:model/PRODUCTSRESPONSE}
     */
    PRODUCTSRESPONSE,

    /**
     * The PRODUCTSRESPONSEDataInner model constructor.
     * @property {module:model/PRODUCTSRESPONSEDataInner}
     */
    PRODUCTSRESPONSEDataInner,

    /**
     * The PRODUCTSVOUCHERCHECK model constructor.
     * @property {module:model/PRODUCTSVOUCHERCHECK}
     */
    PRODUCTSVOUCHERCHECK,

    /**
     * The PRODUCTV model constructor.
     * @property {module:model/PRODUCTV}
     */
    PRODUCTV,

    /**
     * The PRODUCTVENDORLINKG model constructor.
     * @property {module:model/PRODUCTVENDORLINKG}
     */
    PRODUCTVENDORLINKG,

    /**
     * The REQUESTCHECKSTATUSZNS model constructor.
     * @property {module:model/REQUESTCHECKSTATUSZNS}
     */
    REQUESTCHECKSTATUSZNS,

    /**
     * The REQUESTCREATEVOUCHERLINKE model constructor.
     * @property {module:model/REQUESTCREATEVOUCHERLINKE}
     */
    REQUESTCREATEVOUCHERLINKE,

    /**
     * The REQUESTCREATEVOUCHERLINKG model constructor.
     * @property {module:model/REQUESTCREATEVOUCHERLINKG}
     */
    REQUESTCREATEVOUCHERLINKG,

    /**
     * The REQUESTCREATEVOUCHERLINKV model constructor.
     * @property {module:model/REQUESTCREATEVOUCHERLINKV}
     */
    REQUESTCREATEVOUCHERLINKV,

    /**
     * The REQUESTSENDVOUCHERBYEMAIL model constructor.
     * @property {module:model/REQUESTSENDVOUCHERBYEMAIL}
     */
    REQUESTSENDVOUCHERBYEMAIL,

    /**
     * The REQUESTSENDVOUCHERBYSMS model constructor.
     * @property {module:model/REQUESTSENDVOUCHERBYSMS}
     */
    REQUESTSENDVOUCHERBYSMS,

    /**
     * The REQUESTSENDVOUCHERBYZNS model constructor.
     * @property {module:model/REQUESTSENDVOUCHERBYZNS}
     */
    REQUESTSENDVOUCHERBYZNS,

    /**
     * The STOREPAGINGSCHEMA model constructor.
     * @property {module:model/STOREPAGINGSCHEMA}
     */
    STOREPAGINGSCHEMA,

    /**
     * The STOREPRODUCTSCHEMA model constructor.
     * @property {module:model/STOREPRODUCTSCHEMA}
     */
    STOREPRODUCTSCHEMA,

    /**
     * The STORESRESPONSE model constructor.
     * @property {module:model/STORESRESPONSE}
     */
    STORESRESPONSE,

    /**
     * The STORESRESPONSEDataInner model constructor.
     * @property {module:model/STORESRESPONSEDataInner}
     */
    STORESRESPONSEDataInner,

    /**
     * The STORESSCHEMA model constructor.
     * @property {module:model/STORESSCHEMA}
     */
    STORESSCHEMA,

    /**
     * The USAGEMETHODSCHEMA model constructor.
     * @property {module:model/USAGEMETHODSCHEMA}
     */
    USAGEMETHODSCHEMA,

    /**
     * The VENDORSCHEMA model constructor.
     * @property {module:model/VENDORSCHEMA}
     */
    VENDORSCHEMA,

    /**
     * The VOUCHERCHECKRESPONSE model constructor.
     * @property {module:model/VOUCHERCHECKRESPONSE}
     */
    VOUCHERCHECKRESPONSE,

    /**
     * The VOUCHERCHECKSCHEMA model constructor.
     * @property {module:model/VOUCHERCHECKSCHEMA}
     */
    VOUCHERCHECKSCHEMA,

    /**
     * The VOUCHERCHECKSCHEMADETAIL model constructor.
     * @property {module:model/VOUCHERCHECKSCHEMADETAIL}
     */
    VOUCHERCHECKSCHEMADETAIL,

    /**
     * The VOUCHERCHECKZNSRESPONSE model constructor.
     * @property {module:model/VOUCHERCHECKZNSRESPONSE}
     */
    VOUCHERCHECKZNSRESPONSE,

    /**
     * The VOUCHERCHECKZNSRESPONSEData model constructor.
     * @property {module:model/VOUCHERCHECKZNSRESPONSEData}
     */
    VOUCHERCHECKZNSRESPONSEData,

    /**
     * The VOUCHERE model constructor.
     * @property {module:model/VOUCHERE}
     */
    VOUCHERE,

    /**
     * The VOUCHERERESPONSE model constructor.
     * @property {module:model/VOUCHERERESPONSE}
     */
    VOUCHERERESPONSE,

    /**
     * The VOUCHERESCHEMA model constructor.
     * @property {module:model/VOUCHERESCHEMA}
     */
    VOUCHERESCHEMA,

    /**
     * The VOUCHERG model constructor.
     * @property {module:model/VOUCHERG}
     */
    VOUCHERG,

    /**
     * The VOUCHERGRESPONSE model constructor.
     * @property {module:model/VOUCHERGRESPONSE}
     */
    VOUCHERGRESPONSE,

    /**
     * The VOUCHERGSCHEMA model constructor.
     * @property {module:model/VOUCHERGSCHEMA}
     */
    VOUCHERGSCHEMA,

    /**
     * The VOUCHERSENDEMAILRESPONSE model constructor.
     * @property {module:model/VOUCHERSENDEMAILRESPONSE}
     */
    VOUCHERSENDEMAILRESPONSE,

    /**
     * The VOUCHERSENDEMAILSCHEMA model constructor.
     * @property {module:model/VOUCHERSENDEMAILSCHEMA}
     */
    VOUCHERSENDEMAILSCHEMA,

    /**
     * The VOUCHERSENDSMSRESPONSE model constructor.
     * @property {module:model/VOUCHERSENDSMSRESPONSE}
     */
    VOUCHERSENDSMSRESPONSE,

    /**
     * The VOUCHERSENDSMSSCHEMA model constructor.
     * @property {module:model/VOUCHERSENDSMSSCHEMA}
     */
    VOUCHERSENDSMSSCHEMA,

    /**
     * The VOUCHERSENDZNSRESPONSE model constructor.
     * @property {module:model/VOUCHERSENDZNSRESPONSE}
     */
    VOUCHERSENDZNSRESPONSE,

    /**
     * The VOUCHERSENDZNSRESPONSEData model constructor.
     * @property {module:model/VOUCHERSENDZNSRESPONSEData}
     */
    VOUCHERSENDZNSRESPONSEData,

    /**
     * The VOUCHERV model constructor.
     * @property {module:model/VOUCHERV}
     */
    VOUCHERV,

    /**
     * The VOUCHERVRESPONSE model constructor.
     * @property {module:model/VOUCHERVRESPONSE}
     */
    VOUCHERVRESPONSE,

    /**
     * The VOUCHERVSCHEMA model constructor.
     * @property {module:model/VOUCHERVSCHEMA}
     */
    VOUCHERVSCHEMA,

    /**
     * The VOUCHERVSCHEMAProduct model constructor.
     * @property {module:model/VOUCHERVSCHEMAProduct}
     */
    VOUCHERVSCHEMAProduct,

    /**
    * The BrandsApi service constructor.
    * @property {module:api/BrandsApi}
    */
    BrandsApi,

    /**
    * The CategoriesApi service constructor.
    * @property {module:api/CategoriesApi}
    */
    CategoriesApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:api/ProductsApi}
    */
    ProductsApi,

    /**
    * The VoucherApi service constructor.
    * @property {module:api/VoucherApi}
    */
    VoucherApi,

    /**
    * The VoucherSendMethodApi service constructor.
    * @property {module:api/VoucherSendMethodApi}
    */
    VoucherSendMethodApi,

    /**
    * The VoucherStatusApi service constructor.
    * @property {module:api/VoucherStatusApi}
    */
    VoucherStatusApi
};
